CREATE SYNONYM [dbo].[Edfi_StudentEducationOrganizationAssociationStudentIdentificationCode] FOR [s3v5ys_EdFi_BPS_ProdYS_Ods_2023].[edfi].[StudentEducationOrganizationAssociationStudentIdentificationCode]
GO
