CREATE TABLE [dbo].[ActiveStaff_PPLSFT]
(
[ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empl_Rcd#] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eff_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sequence] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deptid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Title] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Entry_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Action] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Action_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empl_Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_Rate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_Freq] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Grade] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Step] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Union_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Indicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orig_Hire_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
