CREATE TABLE [dbo].[staffassignment_Transfer]
(
[ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empl_Rcd#] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eff_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay_Status] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Action] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Action_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position_Entry_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deptid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dept_Title] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Title] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Entry_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Union_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empl_Class] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eff_Date_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pay_Status_Prior] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeptID_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Code_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job_Entry_Date_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Union_Code_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position_Entry_Date_Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empl_Class_Prior] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
